Translate introduction and CAP theorem
Acarus/system-design-primer pull request #8
Opened 2019-01-30 21:28 UTC by Acarus

2019-01-30 21:38 UTC, Kietzmann requested changes

2019-01-30 21:38 UTC, Kietzmann commented on README-uk.md
> +Спочатку, вам потрібно розібратися на базовому рівні із основними поняттями, як їх використовувати, які їх сильні та слабкі сторони.
коми не треба

2019-01-30 21:38 UTC, Kietzmann commented on README-uk.md
> +Далі ми зануримося в більш вузькі розділи такі як DNS, CDNs та балансувальники навантаження(load balancers).
такі як -> , як-от

2019-01-30 21:38 UTC, Kietzmann commented on README-uk.md
> +Ще один спосіб подивитися на відмінність між продуктивностю(performance) та масштабуванням(scalability):
може краще "розглянути відміність" або "розглянути різницю"

2019-01-30 21:38 UTC, Kietzmann commented on README-uk.md
> +У розподіленній комп'ютерній системі можна підтримувати тільки дві властивості з наведених:
розподіленій

2019-01-30 21:38 UTC, Kietzmann commented on README-uk.md
> +* **Стійкість до розподілення(Partition Tolerance)** - Система продовжує функціонувати не зважаючи на випадкові розподілення на ізольовоні секції в результаті мережевих проблем.
незважаючи

2019-01-30 21:38 UTC, Kietzmann commented on README-uk.md
> +* **Стійкість до розподілення(Partition Tolerance)** - Система продовжує функціонувати не зважаючи на випадкові розподілення на ізольовоні секції в результаті мережевих проблем.
" не зважаючи на випадкові розподілення на ізольовоні секції " - тут щось не те

2019-01-30 21:38 UTC, Kietzmann commented on README-uk.md
> +Очікування результату від ізольованого вузла може завершитися помилкою ліміту часу. CP є хорошим рішенням, якщо ваш бізнес потребує атомарні записи і зчитування.
може бізнес поміняти на задачі?

2019-01-30 21:38 UTC, Kietzmann commented on README-uk.md
> +AP є хорошим вибором, якщо ваш бізнес потребує [eventual consistency](#eventual-consistency) чи коли система має продовжувати роботу не зважаючи на зовнішні помилки.
незважаючи

2019-02-02 18:36 UTC, Acarus commented on README-uk.md
> +* **Стійкість до розподілення(Partition Tolerance)** - Система продовжує функціонувати не зважаючи на випадкові розподілення на ізольовоні секції в результаті мережевих проблем.
Що саме? Мається на увазі, що мережа може випадково розпадатися на секції (компоненти зв‘язаності).

2019-02-02 18:37 UTC, Acarus commented on README-uk.md
> +Спочатку, вам потрібно розібратися на базовому рівні із основними поняттями, як їх використовувати, які їх сильні та слабкі сторони.
Якої саме?

2019-02-02 20:39 UTC, Kietzmann commented on README-uk.md
> +Спочатку, вам потрібно розібратися на базовому рівні із основними поняттями, як їх використовувати, які їх сильні та слабкі сторони.
після спочатку

2019-02-02 20:40 UTC, Kietzmann commented on README-uk.md
> +* **Стійкість до розподілення(Partition Tolerance)** - Система продовжує функціонувати не зважаючи на випадкові розподілення на ізольовоні секції в результаті мережевих проблем.
може краще розподіли на ізольовані секції
або розділення на ізольовані секції

2019-02-03 15:21 UTC, Kietzmann commented on README-uk.md
> +Далі, ми розглянемо базові компроміси:
коми не треба
та і далі "можна" прибрати

2019-02-03 15:21 UTC, Kietzmann commented on README-uk.md
> +Спочатку вам потрібно розібратися на базовому рівні із основними поняттями, як їх використовувати, які їх сильні та слабкі сторони.
їх їх
може краще "їх використанням та перевагами і недоліками"?

2019-02-03 15:21 UTC, Kietzmann commented on README-uk.md
> +В загальгому випадку, наша ціль це **максимальна пропускна здатність** з **припустимою латентністю**.
загальгому
наша ціль - це
припустимою - допустимою

2019-02-03 15:21 UTC, Kietzmann commented on README-uk.md
> +В загальгому випадку, наша ціль це **максимальна пропускна здатність** з **припустимою латентністю**.
або прийнятною

2019-02-03 15:21 UTC, Kietzmann commented on README-uk.md
> +В загальгому випадку, наша ціль це **максимальна пропускна здатність** з **припустимою латентністю**.
хоча може й допустимою правильно

2019-02-03 15:28 UTC, Acarus commented on README-uk.md
> +Спочатку вам потрібно розібратися на базовому рівні із основними поняттями, як їх використовувати, які їх сильні та слабкі сторони.
+, але заміню "та" на кому, бо якось два сполучника підряд важко читається. 
"їх використанням, перевагами та недоліками"

2019-02-03 15:38 UTC, merged